# Generated by Django 5.2.4 on 2025-07-27 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('form_number', models.CharField(max_length=32, unique=True)),
                ('submitted_date', models.DateTimeField()),
                ('axle_box_housing_bore_dia', models.CharField(blank=True, max_length=100, null=True)),
                ('bearing_seat_diameter', models.CharField(blank=True, max_length=32, null=True)),
                ('condemning_dia', models.CharField(blank=True, max_length=32, null=True)),
                ('intermediate_wwp', models.CharField(blank=True, max_length=32, null=True)),
                ('last_shop_issue_size', models.CharField(blank=True, max_length=32, null=True)),
                ('roller_bearing_bore_dia', models.CharField(blank=True, max_length=32, null=True)),
                ('roller_bearing_outer_dia', models.CharField(blank=True, max_length=32, null=True)),
                ('roller_bearing_width', models.CharField(blank=True, max_length=32, null=True)),
                ('tread_diameter_new', models.CharField(blank=True, max_length=32, null=True)),
                ('variation_same_axle', models.CharField(blank=True, max_length=32, null=True)),
                ('variation_same_bogie', models.CharField(blank=True, max_length=32, null=True)),
                ('variation_same_coach', models.CharField(blank=True, max_length=32, null=True)),
                ('wheel_disc_width', models.CharField(blank=True, max_length=32, null=True)),
                ('wheel_gauge', models.CharField(blank=True, max_length=32, null=True)),
                ('wheel_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('extras', models.JSONField(default=dict)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
